added "modal" to sidenav in every page.
zoyatanweer/falcon-ui pull request #10
Opened 2022-02-18 14:18 UTC by zoyatanweer

2022-02-18 17:21 UTC, rutu14 approved these changes

2022-02-18 17:24 UTC, dev-prabhat requested changes
Looks good to me

2022-02-18 17:24 UTC, dev-prabhat commented on components/avatar/avatar.html
> +                <a class="link link-active" href="/index.html">HOME</a>
you can also add href="/" i think it works fine

2022-02-18 17:26 UTC, bossmonkey98 commented
Try to make it responsive

2022-02-18 17:26 UTC, bossmonkey98 approved these changes

2022-02-18 17:42 UTC, zoef-yt approved these changes
The code looks good. Good to merge with the minor change.

2022-02-18 17:42 UTC, zoef-yt commented on components/badge/badge.css
> +    left: 25px;
use rem.

2022-02-18 17:54 UTC, Muzammil-khan710 approved these changes

2022-02-19 08:33 UTC, zoyatanweer commented
- added installation link in index.html
- changed the secondary color of button 
- changed the hover state of outlined button

2022-02-19 08:34 UTC, merged