Lists and toast component
zoyatanweer/falcon-ui pull request #14
Opened 2022-03-15 10:17 UTC by zoyatanweer

- added ordered, unordered and stacked list.
-  added components in the side navigation bar.
- added toast component.

![image](https://user-images.githubusercontent.com/87615284/158355997-0fcd3b32-84ec-49af-bfaa-2501efd1ec51.png)
![image](https://user-images.githubusercontent.com/87615284/158356179-3c393485-0df4-4e3b-b2f5-7535867161d6.png)
![image](https://user-images.githubusercontent.com/87615284/158356475-3590e53f-2fd7-494e-841e-ba8052ea4f85.png)
![Uploading image.png…]()

2022-03-15 11:06 UTC, dev-prabhat requested changes
Components are clean and looks great   Code is clean, readable and just some irregular spacing but CSS classes

2022-03-15 11:06 UTC, dev-prabhat commented on components/toast/toast.css
> +.toast-svg{
irregular spacing between classes

2022-03-15 11:27 UTC, srishtigautam21 commented on components/lists/lists.css
> +    margin-left: 17px;
you can use rem here

2022-03-15 11:29 UTC, srishtigautam21 approved these changes
looks good to merge with the suggested changes
Appreciation:The UI looks very clean

2022-03-15 13:26 UTC, zoyatanweer commented on components/toast/toast.css
> +.toast-svg{
ok i will remove that

2022-03-15 13:26 UTC, zoyatanweer commented on components/lists/lists.css
> +    margin-left: 17px;
sure srishti

2022-03-15 13:27 UTC, zoyatanweer commented
thank you Prabhat and Srishti for your reviews.

2022-03-15 14:52 UTC, zoef-yt approved these changes
The code looks good to me with all the changes.
1. The UI looks really good.
2. The code is simple and understandable
3. Nice use of comments to show the components starts.

Good to merge. Good work.

2022-04-01 10:04 UTC, srishtigautam21 approved these changes
clean and understandable code
good to merge

2022-04-07 14:58 UTC, itsmebipul00 approved these changes
Good to merge

2022-04-07 17:08 UTC, merged