added button component.
zoyatanweer/falcon-ui pull request #3
Opened 2022-02-05 07:44 UTC by zoyatanweer

2022-02-05 08:14 UTC, DivyanshSareen commented
<img width="383" alt="image" src="https://user-images.githubusercontent.com/59335572/152634101-15862df1-b40d-4272-94d1-bd052e84e423.png">

you can align the text with the icon here

2022-02-05 08:28 UTC, zoef-yt requested changes
Do the suggested changes

2022-02-05 08:28 UTC, zoef-yt commented on css/common.css
>      /* background-color: #56cfe1; */
remove commented code.

2022-02-05 08:28 UTC, zoef-yt commented on css/common.css
> +    /* font-size:1.2rem; */
remove commented code.

2022-02-05 08:28 UTC, zoef-yt commented on css/common.css
> +    /* padding-top:4rem; */
remove commented code.

2022-02-05 08:28 UTC, zoef-yt commented on css/common.css
> +    /* width: 200px; */
remove commented code.

2022-02-05 08:28 UTC, zoef-yt commented on css/common.css
> +    /* font-size: 1.8rem; */
remove commented code.

2022-02-05 09:40 UTC, dev-prabhat approved these changes
Looks good to me

2022-02-05 13:41 UTC, zoef-yt requested changes

2022-02-05 13:41 UTC, zoef-yt commented on components/button/button.css
> +    font-size: 30px;
Use rem

2022-02-05 13:41 UTC, zoef-yt commented on components/button/button.css
>    .btn-floating-action{
use variable in the below code.

2022-02-06 08:29 UTC, zoef-yt requested changes

2022-02-06 08:29 UTC, zoef-yt commented on css/common.css
> +    /* margin:1rem auto 1rem 4.8rem; */
remove commented code

2022-02-06 08:29 UTC, zoef-yt commented on css/common.css
> +    /* margin: 0 1rem; */
remove commented code

2022-02-06 08:29 UTC, zoef-yt commented on css/common.css
> +    padding: 20px 10px;
use rem

2022-02-06 09:15 UTC, zoef-yt approved these changes
Good code. Good to megre?

2022-02-06 12:44 UTC, merged

2022-04-02 07:38 UTC, jDineshKarthic commented
The items (icon and the text) and not aligned properly in the same line. Try adding 
display :flex;
align-items: center; for all the button tags. 
And add display: flex , to the container div tag.
![button](https://user-images.githubusercontent.com/73705032/161372428-10582a9b-1c47-4cf9-8074-2f44555e8bce.JPG)